#!/bin/csh -f

set nonomatch
set path = (/usr/local/telescope/bin $path)
set base_image_dir = '/exports/images'
set now = `date`
echo "Decomp started at $now"

foreach fname (astrophysics external faculty general modern solarsys research) 
  find $base_image_dir/$fname/images/ -name \*.fth\
   -exec /usr/local/telescope/bin/fdecompress -r {} \;
end
 
set now = `date`
echo "Decomp end at $now"
