#! /usr/bin/env python

'''
Converts 32 bit FITS images to 16 bit for Talon software e.g. camera
FITS filename can be wild-carded e.g. *.fts in current directory
Warning: Overwrites original file(s)

RLM 30 Oct 2014
'''

import pyfits, os, sys, glob


# === MAIN ===
# get filenames
fnames = glob.glob(sys.argv[1])
print fnames
for fn in fnames:
	print fn
	HDU = pyfits.open(fn)
	Im = HDU[0].data; Header= HDU[0].header
	HDU[0].scale('int16', bzero = 32768)
	os.remove(fn); HDU.writeto(fn)
print 'Done'
