#!/usr/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'fundamentals==0.9.1','console_scripts','mysqlSucker'
__requires__ = 'fundamentals==0.9.1'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('fundamentals==0.9.1', 'console_scripts', 'mysqlSucker')()
    )
