#!/usr/bin/perl
# distemail.pl: send email to everyone with new images update emaillog.
# Elwood Downey
#  6 Sep 96: first release
# 10 Sep 96: change mail format slightly and enable for all users.
# 16 Sep 96: tighten up emaillog
# 17 Sep 96: improve keywords around/for each feature
#  6 Nov 98: changes for iro/atf. no more obs log
# 19 Nov 04: fixed paths
# 24 Nov 04: fix telhome; add 24 argument
# 22 Oct 05: change paths for deimos, change emaillog destination to user/logs [rlm]
#  8 Mar 07: allow multiple email addresses for each code [bmp]
# 20 Oct 12: check student_*.obs files for student codes, new email format [bmp]
# 23 Nov 15 do not  actually send email (replaced by email_summary) [rlm]

# only send mail if images are no older than this many seconds from now.
# may be overridden with first argument.
$age = defined($ARGV[0]) ? 3600*$ARGV[0] : 1e10;   # N.B. want age in seconds
if ($age <= 0) {
    $_ = $0; s#.*/##;
    print "Usage: $_ [age]\n";
    print "Purpose: send email to owners of \$TELHOME/user/images.\n";
    print "Default is to send mail to everyone regardless of file age.\n";
    print "First optional arg can specify a max age, in hours.\n";
    exit 1;
}

# need TELHOME
#defined($telhome = $ENV{TELHOME}) or die "No TELHOME\n";
$telhome = "/usr/local/telescope";

# dir with images to inspect
$imdir = "$telhome/user/images";

# dir with schedules to hunt for additional emails to notify -BMP
$scheddir = "$telhome/user/schedin/netin";

# file of user codes with email addresses
@obsinfo = `cat $telhome/user/obsinfo/obs.txt`;

# student observer code files -BMP
@studentobs = `cat $telhome/user/obsinfo/studentobs_?.txt`;

# file in which we append email activity
$logfn = "$telhome/archive/logs/emaillog";

# open log file for append
open(LOG, ">>$logfn") or die "Can not append to $logfn\n";

# add date stamp and auxmsg
($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdst) = gmtime();
$mon += 1;
$year += 1900;
print LOG "DATE: $mon/$mday/$year $hour:$min:$sec MDY UTC\n";
print LOG "\n";

# scan image directory for new files, get codes from filenames
$now = time();
foreach $fn (<$imdir/???*.ft[sh]>) {
    my ($dev,$ino,$mode,$nlink,$uid,$gid,$rdev,$size,
			  $atime,$mtime,$ctime,$blksize,$blocks) = stat($fn);
    next if ($mtime + $age < $now);
    $fn =~ s#.*/##;
    $obc = substr($fn,0,3);
    if (!grep /$obc/,@obscodes) {
        push(@obscodes,$obc);
    }
}

# find new files for each code, get emails and send
foreach $obc (@obscodes) {
    @files=();
    @emails=();
    foreach $fn (<$imdir/$obc*.ft[sh]>) {
        my ($dev,$ino,$mode,$nlink,$uid,$gid,$rdev,$size,
			  $atime,$mtime,$ctime,$blksize,$blocks) = stat($fn);
        next if ($mtime + $age < $now);
        $fn =~ s#.*/##;
        push(@files,$fn);
    }
    if (@x=grep /^$obc /,(@obsinfo, @studentobs) ) {
        @y=split(/\s*\|\s/,@x[0]);
        @emails=split(",",$y[1]);
        foreach $sch (glob "$scheddir/$obc*.sch") {
            foreach $line (grep /\@/,`cat $sch`) {
                ($a)=($line =~ /([^\'\s]+\@[^\'\s]+)/);
                if (!grep /$a/,@emails) {
                    push(@emails, $a);
                }
            }
        }
	&sendEmail();
    }
}
    
# send email to @emails and tell them @files are ready
# also append to $logfn
sub sendEmail
{
  foreach $email (@emails) {
    my ($msg,$fmtfiles,$n,$f);
    $n = 0;
    foreach $f (@files) {
	$fmtfiles .= "\n " if (($n++ % 5) == 0);
	$fmtfiles .= " $f";
    }

    # build the message
    $msg = <<"xEOFx";
This message is being generated automatically by the University of Iowa's Robotic Telescope Facility. The images taken at your request are now available. The resulting files are listed below.

Images are hosted on the server deimos.physics.uiowa.edu. In the astronomy labs, these images can be found on the 'student-images' drive. External observers can connect to the server via web browser or anonymous ftp. Images are stored in directories based on the observer type, the first three letters of the filename, the year, and the day of the year (the first three numbers in the filename).

Images will remain online for two weeks, after which they may be archived. Archived images can be restored by special request. Please direct any questions to talon\@deimos.physics.uiowa.edu.

Thank you.
$fmtfiles


xEOFx

    # send mail
    #if (!open (M, "| mail -s 'Your Rigel images are ready' \"$email\"")) {
    #	print STDERR "Can not send mail to $email\n";
    #	return;
    #}
    #print M $msg;
    #close (M);

    # append name, address and files to log
    #print LOG "EMAIL: $addr\n";
    #print LOG "NAME: $name\n";
    #print LOG "FILES: @files\n";
    #print LOG "\n";
  }
}

# For RCS Only -- Do Not Edit
# @(#) $RCSfile: distemail.pl,v $ $Date: 2001/04/19 21:12:16 $ $Revision: 1.1.1.1 $ $Name:  $
