! Generated by submit_sched.pl Version 3.1
! For the Rigel Telescope.
! From  (128.255.44.84)
! As Observer Code "gad"
! On Tue Apr  7 18:30:47 UTC 2015
! With Mozilla/5.0 (X11; Linux x86_64; rv:35.0) Gecko/20100101 Firefox/35.0

TITLE = 'Jupiter Mass'
OBSERVER = 'nick-becker@uiowa.edu'
PRIORITY = '10'

SOURCE = 'Jupiter'
FILTER = 'N' DURATION = '1'
/
SOURCE = 'Jupiter'
FILTER = 'N' DURATION = '0.5'
/
SOURCE = 'Jupiter'
FILTER = 'N' DURATION = '0.1'
/
