! Generated by submit_sched.pl Version 3.1
! For the Rigel Telescope.
! From  (173.17.168.76)
! As Observer Code "mai"
! On Sat Apr 25 17:27:54 UTC 2015
! With Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36

TITLE = 'Saturn'
OBSERVER = 'ryan-sotern@uiowa.edu'
PRIORITY = '10'

SOURCE = 'Saturn'
FILTER = 'B' DURATION = '.25'
/
SOURCE = 'Saturn'
FILTER = 'B' DURATION = '.5'
/
SOURCE = 'Saturn'
FILTER = 'B' DURATION = '1'
/
