! Generated by submit_sched.pl Version 3.1
! For the Rigel Telescope.
! From  (172.23.24.134)
! As Observer Code "mak"
! On Fri Apr 24 23:52:56 UTC 2015
! With Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36

TITLE = 'Jupiters Mass'
OBSERVER = 'ryan-sullivan-1@uiowa.edu'
OBSERVER = 'logan-lawler@uiowa.edu'
OBSERVER = 'michael-sylvester@uiowa.edu'
PRIORITY = '10'

SOURCE = 'Jupiter'
FILTER = 'B' DURATION = '.05'
/
SOURCE = 'Jupiter'
FILTER = 'H' DURATION = '1'
/
