! Generated by submit_sched.pl Version 3.1
! For the Rigel Telescope.
! From  (173.28.198.174)
! As Observer Code "mdb"
! On Fri Apr 24 23:27:30 UTC 2015
! With Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36

TITLE = 'Finding the mass of Jupiter'
OBSERVER = 'joseph-leiferman@uiowa.edu'
OBSERVER = 'chi-zhang@uiowa.edu'
PRIORITY = '10'

BLOCK = '1:00:00' 
SOURCE = 'Jupiter'
FILTER = 'N' DURATION = '1'
/
BLOCKREPEAT 5

