! Generated by submit_sched.pl Version 3.1
! For the Rigel Telescope.
! From  (172.23.100.151)
! As Observer Code "mec"
! On Fri Apr 24 16:56:21 UTC 2015
! With Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36

TITLE = 'Ganymede JMass'
OBSERVER = 'matthew-ehler@uiowa.edu'
PRIORITY = '10'

SOURCE = 'Jupiter'
LSTSTART = '10:10:59' UTDATE = 04/25/2015
FILTER = 'B' DURATION = '.1'
/
SOURCE = 'Jupiter'
LSTSTART = '13:11:28' UTDATE = 04/25/2015
FILTER = 'B' DURATION = '.1'
/
