! Generated by submit_sched.pl Version 3.1
! For the Rigel Telescope.
! From  (128.255.34.50)
! As Observer Code "mfj"
! On Fri Apr 24 17:16:35 UTC 2015
! With Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/600.5.17 (KHTML, like Gecko) Version/6.2.5 Safari/537.85.14

TITLE = 'jupiters moon'
OBSERVER = 'liam-sutton@uiowa.edu'
PRIORITY = '10'

BLOCK = '1:00:00' 
SOURCE = 'jupiter'
LSTSTART = '9:50:00'
UTDATE = 04/25/2015
FILTER = 'B' DURATION = '0.5'
/
BLOCKREPEAT 7

