! Generated by submit_sched.pl Version 3.1
! For the Rigel Telescope.
! From  (128.255.34.46)
! As Observer Code "xea"
! On Fri Apr 24 00:49:45 UTC 2015
! With Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/600.5.17 (KHTML, like Gecko) Version/6.2.5 Safari/537.85.14

TITLE = 'Asteroid hunt '
OBSERVER = 'wot.sage@gmail.com'
PRIORITY = '100'

BLOCK = '0:45:00' 
SOURCE = 'Field 1'
RA = '14:22:52' DEC = '-14:09:40' EPOCH = '2000'
UTDATE = 04/25/2015
FILTER = 'R' DURATION = '60'
/
BLOCKREPEAT 9

BLOCK = '0:45:00' 
SOURCE = 'Field 2'
RA = '14:24:52.1' DEC = '-14:21:13.8' EPOCH = '2000'
UTDATE = 04/25/2015
FILTER = 'R' DURATION = '60'
/
BLOCKREPEAT 9

BLOCK = '0:45:00' 
SOURCE = 'Field 3'
RA = '14:27:38.5' DEC = '-14:38:42' EPOCH = '2000'
UTDATE = 04/25/2015
FILTER = 'R' DURATION = '60'
/
BLOCKREPEAT 9

BLOCK = '0:45:00' 
SOURCE = 'Field 4'
RA = '14:22:37' DEC = '-14:03:08' EPOCH = '2000'
UTDATE = 04/25/2015
FILTER = 'R' DURATION = '60'
/
BLOCKREPEAT 9

BLOCK = '0:45:00' 
SOURCE = 'Field 5 '
RA = '14:19:33' DEC = '-13:54:48 ' EPOCH = '2000'
UTDATE = 04/28/2015
FILTER = 'R' DURATION = '60'
/
BLOCKREPEAT 9

