! Generated by Sierra Stars Observatory
! By Observer IsD: glbates
! On UTC 04/24/2015


Title = 'M88'
OBSERVER = 'G Bates'
Block = '00:08:00'

    SOURCE = 'M88'
    FILTER = 'B,R,V'
    DURATION = '150,150,150'
    BINNING = '2,2'
    RA = '12:31:59'
    DEC = '14:25:11'
    EPOCH = 2000
    PRIORITY = 5
    COMPRESS = 0
    IMAGEDIR = '/usr/local/telescope/user/images/'
    COMMENT = 42810
    REPEAT = 1
    /
    BLOCKREPEAT  = 2
