! Generated by Sierra Stars Observatory
! By Observer IsD: DaveDowhos
! On UTC 04/24/2015
!! Extra: fitsheader USERNAME=DDJ


Title = 'AM Her #11'
OBSERVER = 'D J Dowhos'
Block = '00:00:00'

    SOURCE = 'AM Her'
    FILTER = 'V'
    DURATION = '30'
    BINNING = '2,2'
    RA = '18:14:59.'
    DEC = '49:50:48'
    EPOCH = 1950
    PRIORITY = 5
    COMPRESS = 0
    IMAGEDIR = '/usr/local/telescope/user/images/'
    COMMENT = 42814
    REPEAT = 1
    /
    BLOCKREPEAT  = 1
