! Generated by Sierra Stars Observatory
! By Observer IsD: glbates
! On UTC 04/24/2015


Title = 'm104'
OBSERVER = 'G Bates'
Block = '00:00:30'

    SOURCE = 'M104'
    FILTER = 'N'
    DURATION = '180'
    BINNING = '2,2'
    RA = '12:39:59.3'
    DEC = '-11:37:21'
    EPOCH = 2000
    PRIORITY = 5
    COMPRESS = 0
    IMAGEDIR = '/usr/local/telescope/user/images/'
    COMMENT = 42811
    REPEAT = 1
    /
    BLOCKREPEAT  = 5
