! Generated by Sierra Stars Observatory
! By Observer IsD: augustinus
! On UTC 04/24/2015


Title = 'Waarneming dubbelster'
OBSERVER = 'Hans,Emiel en Lennert'
Block = '00:00:30'

    SOURCE = 'HIP4288 A'
    FILTER = 'R'
    DURATION = '15'
    BINNING = '2,2'
    RA = '00:54:58'
    DEC = '23:37:41'
    EPOCH = 2000
    PRIORITY = 5
    COMPRESS = 0
    IMAGEDIR = '/usr/local/telescope/user/images/'
    COMMENT = 42721
    REPEAT = 1
    /
    BLOCKREPEAT  = 1
