! Generated by Sierra Stars Observatory
! By Observer IsD: DaveDowhos
! On UTC 04/24/2015
!! Extra: fitsheader USERNAME=DDJ


Title = 'BF Cyg #5'
OBSERVER = 'Dave Dowhos'
Block = '00:00:30'

    SOURCE = 'BF Cyg'
    FILTER = 'V'
    DURATION = '30'
    BINNING = '2,2'
    RA = '19:21:55.'
    DEC = '29:34:36'
    EPOCH = 1950
    PRIORITY = 5
    COMPRESS = 0
    IMAGEDIR = '/usr/local/telescope/user/images/'
    COMMENT = 42798
    REPEAT = 1
    /
    BLOCKREPEAT  = 1
