! Generated by submit_sched.pl Version 3.1
! For the Rigel Telescope.
! From  (128.255.35.95)
! As Observer Code "frm"
! On Tue Dec  9 23:23:06 UTC 2014
! With Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/600.1.25 (KHTML, like Gecko) Version/8.0 Safari/600.1.25

TITLE = 'SN in NGC4666 (AT #6795), Comet Lovejoy'
OBSERVER = 'robert-mutel@uiowa.edu'
PRIORITY = '10'
LSTSTART 11:30:00

BLOCK = '0:00:00' 
SOURCE = 'NGC4666'
FILTER = 'N' DURATION = '60'
/
BLOCKREPEAT 6

BLOCK = '0:00:00' 
SOURCE = 'NGC4666'
FILTER = 'B' DURATION = '60'
/
BLOCKREPEAT 6

BLOCK = '0:00:00' 
SOURCE = 'NGC4666'
FILTER = 'V' DURATION = '60'
/
BLOCKREPEAT 6

BLOCK = '0:00:00' 
SOURCE = 'NGC4666'
FILTER = 'R' DURATION = '60'
/
BLOCKREPEAT 6

BLOCK = '0:00:00' 
SOURCE = 'NGC4666'
FILTER = 'I' DURATION = '60'
/
BLOCKREPEAT 6
source 'C/2014 Q2 (Lovejoy)' lststart 04:00:00 filter n,b,v,r dur 120,120,120,120 repeat 2 /
source 'alpha com' ra 13:09:59.3 dec 17:31:46 epoch 2000 lststart 12:00:00 filter b,v,r,i dur 0.1,0.1,0.1,0.1 repeat 2 /
