#!/usr/bin/env python

# rename a directory of files to include their filter and exposure

import glob
import sys
from os import rename as rn

import numpy as np
from astropy.io import fits


def rename(files, obj, ftr, tim, loc="/exports/images/research/images/xjk/2022/"):
    global day
    loc_ = loc + day + "/"
    for i, fp in enumerate(files):
        rn(
            fp,
            loc
            + day
            + "/"
            + obj[i]
            + "_"
            + ftr[i]
            + "_"
            + tim[i]
            + "s_"
            + str(i)
            + ".fts",
        )


def FileSort(filepaths):
    objs = []
    filters = []
    exptimes = []

    for file in filepaths:
        objs.append((fits.open(file)[0].header)["OBJECT"])
        filters.append((fits.open(file)[0].header)["FILTER"])
        temp = (fits.open(file)[0].header)["EXPTIME"]
        exptimes.append(str(temp)[: str(temp).index(".")])
    return list(zip(filepaths, objs, filters, exptimes))


day = input("Which Day? ")
dir_fp = "/exports/images/research/images/xjk/2022/" + day
fps = glob.glob(dir_fp + "/*.fts")
dir_data = FileSort(fps)

objs = []
ftrs = []
exps = []
for data in dir_data:
    objs.append(data[1])
    ftrs.append(data[2])
    exps.append(data[3])


rename(fps, objs, ftrs, exps)

exit()
