#!/usr/bin/env python

import os
top_dir = os.getcwd()

for root, dirs, files in os.walk(".", topdown=True):
	for name in files:
		if 'fts' in name: 
		    ftsfile = name
		    fullpath = '%s/%s' % (top_dir,root[2:])
		    if '-' in ftsfile:
		        newfile = ftsfile.replace('-','_')
		        old = '%s/%s' % (fullpath,ftsfile)
		        new = '%s/%s' % (fullpath,newfile)
		        os.rename(old,new)
		        print 'Renamed %s to %s' % (ftsfile, newfile)
		    
